### PR TITLE
CH EMED EPR: Fix type of requester setter and getter

### LINKED ISSUE #150: CH EMED EPR: MedicationRequest.requester type can be improved
In `ChEmedEprMedicationRequest`, we use `Author` as type for the requester, whereas it can only be a PractitionerRole [in the IG](https://fhir.ch/ig/ch-emed-epr/StructureDefinition-ch-emed-epr-medicationrequest.html).

### PR DESCRIPTION
**Pull request by qligier**
Fixes #150

### CODE REVIEW

File: husky-fhir/husky-fhir-emed-ch/husky-fhir-emed-ch-epr/src/main/java/org/projecthusky/fhir/emed/ch/epr/resource/ChEmedEprMedicationRequest.java [hunk 1]
```diff
@@ -417,7 +421,7 @@ public void copyValues(final MedicationRequest dst) {
     @Override
     @ExpectsValidResource
     public Author resolveMedicalAuthor() {
-        return resolveRequester();
+        return new Author(this.resolveRequester());
```
Comment (dvribeira) [inline husky-fhir/husky-fhir-emed-ch/husky-fhir-emed-ch-epr/src/main/java/org/projecthusky/fhir/emed/ch/epr/resource/ChEmedEprMedicationRequest.java:424]:
```suggestion
        return new Author(this.resolveRequester(), this.resolveAuthoredOn());
```

Comment (dvribeira) [reply husky-fhir/husky-fhir-emed-ch/husky-fhir-emed-ch-epr/src/main/java/org/projecthusky/fhir/emed/ch/epr/resource/ChEmedEprMedicationRequest.java:424]: Unless you object for some reason, I'd prefer to keep the authorship timestamp information on the reply of this method.

**Review by dvribeira — CHANGES_REQUESTED** [review]

File: husky-fhir/husky-fhir-emed-ch/husky-fhir-emed-ch-epr/src/main/java/org/projecthusky/fhir/emed/ch/epr/resource/ChEmedEprMedicationRequest.java (hunk 1 above)
Comment (qligier) [reply husky-fhir/husky-fhir-emed-ch/husky-fhir-emed-ch-epr/src/main/java/org/projecthusky/fhir/emed/ch/epr/resource/ChEmedEprMedicationRequest.java:424]: I agree, it was not my intent to remove it. I saw that when working on #154

**Review by dvribeira — APPROVED** [review]
